language: node_js
node_js:
    - '12'
dist: trusty
sudo: required
addons:
    chrome: stable
    hostname: localhost
services:
    - mongodb
    - redis-server
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
    - yarn start &
cache:
    yarn: true
    directories:
        - node_modules
        - client/node_modules
install:
    - yarn install
    - yarn build
script:
    - yarn test
