language: node_js
node_js:
    - '12'
dist: trusty
services:
    - mongodb
    - redis-server
env:
    - MONGODB_URI='mongodb://127.0.0.1:27017/blog_ci'
    - REDIS_URL='redis://127.0.0.1:6379'
    - PORT=3000
    - NODE_ENV='production'
cache:
    directories:
        - node_modules
        - client/node_modules
install:
    - yarn install
    - yarn build
script:
    - nohup yarn start
    - sleep 3
    - yarn test
